# LEGAL NOTICE
# This computer software was prepared by Battelle Memorial Institute,
# hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830
# with the Department of Energy (DOE). NEITHER THE GOVERNMENT NOR THE
# CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
# LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this
# sentence must appear on any copies of this computer software.
# 
# EXPORT CONTROL
# User agrees that the Software will not be shipped, transferred or
# exported into any country or used in any manner prohibited by the
# United States Export Administration Act or any other applicable
# export laws, restrictions or regulations (collectively the "Export Laws").
# Export of the Software may require some form of license or other
# authority from the U.S. Government, and failure to obtain such
# export control license may result in criminal liability under
# U.S. laws. In addition, if the Software is identified as export controlled
# items under the Export Laws, User represents and warrants that User
# is not a citizen, or otherwise located within, an embargoed nation
# (including without limitation Iran, Syria, Sudan, Cuba, and North Korea)
#     and that User is not otherwise prohibited
# under the Export Laws from receiving the Software.
# 
# Copyright 2011 Battelle Memorial Institute.  All Rights Reserved.
# Distributed as open-source under the terms of the Educational Community 
# License version 2.0 (ECL 2.0). http://www.opensource.org/licenses/ecl2.php
# 
# For further details, see: http://www.globalchange.umd.edu/models/gcam/
#

# diag_header.R
#
# An automated graphing system to process GCAM output data (as generated by the
# ModelInterface) and generate both standard and user-defined graphs.
#
# This file provides various facilities, including logging, file I/O and settings
#
# Ben Bond-Lamberty, November 2012

# -----------------------------------------------------------------------------
# Logger settings
LOGLEVEL_DEBUG      <- 4
LOGLEVEL_DETAIL     <- 3
LOGLEVEL_SUMMARY    <- 2
LOGLEVEL_ERROR      <- 1
LOGLEVEL_NONE       <- 0
LOGLEVEL            <- LOGLEVEL_DEBUG

# -----------------------------------------------------------------------------
# printlog: time-stamped output
# params: msg (message", " can be many items); ts (add timestamp?), cr (print CR?)
printlog <- function( msg, ..., ts=TRUE, cr=TRUE, level=LOGLEVEL_DEBUG ) {
    if( level <= LOGLEVEL ) {
        if( ts ) cat( date(), GCAM_SOURCE_FN[ GCAM_SOURCE_RD ], "[", GCAM_SOURCE_RD, "]", ": " )
        cat( msg, ... )
        if( cr ) cat( "\n")
    }
}

# -----------------------------------------------------------------------------
# logstart: start a new log (to screen and optionally file)
# params: fn (name of source file being executed), savelog (whether to write to disk)
logstart <- function( fn, savelog=T ) {
    GCAM_SOURCE_RD <<- GCAM_SOURCE_RD + 1       # push
    GCAM_SOURCE_FN[ GCAM_SOURCE_RD ]  <<- fn
    GCAM_LOG_SAVE[ GCAM_SOURCE_RD ] <<- savelog
    logpath <- "logs"
    if( !file.exists( logpath ) )
        dir.create( logpath )
    if( savelog ) sink( paste( logpath, "/", fn, ".log", sep="" ), split=T )
    printlog( "-----" )
    printlog( "Starting", fn )
    
    DEPENDENCIES[[ fn ]] <<- c( NULL ) # Create a new entry in the dependency list
}

# -----------------------------------------------------------------------------
# logstop: stop the current log (to screen and optionally file)
logstop <- function() {

    fn <- GCAM_SOURCE_FN[ GCAM_SOURCE_RD ]

    printlog( "All done with", fn )
    if( GCAM_SOURCE_RD > 0 ) {
        if( GCAM_LOG_SAVE[ GCAM_SOURCE_RD ] ) sink()
        GCAM_SOURCE_RD <<- GCAM_SOURCE_RD - 1       # pop
    } else {
        printlog( "WARNING: Attempt to close a non-open log file")
    }
}
