# LEGAL NOTICE
# This computer software was prepared by Battelle Memorial Institute,
# hereinafter the Contractor, under Contract No. DE-AC05-76RL0 1830
# with the Department of Energy (DOE). NEITHER THE GOVERNMENT NOR THE
# CONTRACTOR MAKES ANY WARRANTY, EXPRESS OR IMPLIED, OR ASSUMES ANY
# LIABILITY FOR THE USE OF THIS SOFTWARE. This notice including this
# sentence must appear on any copies of this computer software.
#
# EXPORT CONTROL
# User agrees that the Software will not be shipped, transferred or
# exported into any country or used in any manner prohibited by the
# United States Export Administration Act or any other applicable
# export laws, restrictions or regulations (collectively the "Export Laws").
# Export of the Software may require some form of license or other
# authority from the U.S. Government, and failure to obtain such
# export control license may result in criminal liability under
# U.S. laws. In addition, if the Software is identified as export
# controlled items under the Export Laws, User represents and warrants
# that User is not a citizen, or otherwise located within, an embargoed
# nation (including without limitation Iran, Syria, Sudan, Cuba, and
# North Korea) and that User is not otherwise prohibited under the
# Export Laws from receiving the Software.
#
# Copyright 2011 Battelle Memorial Institute.  All Rights Reserved.
# Distributed as open-source under the terms of the Educational Community
# License version 2.0 (ECL 2.0). http://www.opensource.org/licenses/ecl2.php
#
# For further details, see: http://www.globalchange.umd.edu/models/gcam/


# diagnostics_USA.R
#
# An automated graphing system to process GCAM output data (as generated by the
# ModelInterface) and generate both standard and user-defined graphs.
#
# This file is the main entry point to the backend system.
#
# Ben Bond-Lamberty, November 2012
# Matthew Binsted, August 2017


# Load all support functions into memory
source( "scripts/diag_header_USA.R" )	# configuration and helper functions
source( "scripts/color_schemes_USA.R" ) # some predefined color schemes

library("reshape2")
library("stringr")
library("scales")
library("plyr")
library("readr")
library("tidyr")
library("dplyr")
library("rgcam")
library("gcamdata")

logstart( "diagnostics.R", savelog=F )

# ============================================================================
# RGCAM
# Connect a GCAM database using rgcam, run batch query on new scenarios and add to prj (if needed)

# Core DB
# conn <- localDBConn('../_DBs', 'database_basexdb_core')
# prj <- addScenario(conn, 'GCAM_USA_BYU_Ref.dat', 'GCAM-USA_ref', 'batch_queries_USA_BYupdate.xml')

# # BYU DB
# conn <- localDBConn('../_DBs', 'database_basexdb_BYU')
# prj <- addScenario(conn, 'GCAM_USA_Ref.dat', 'GCAM-USA_BYU_Ref', 'batch_queries_USA_BYupdate.xml')

# Load existing rgam project file (if one exists)
prj <- loadProject('GCAM_USA_BYU.dat')
scenarios <- listScenarios(prj)
queries <- listQueries(prj, 'GCAM-USA_Ref')

# ============================================================================
# Other data to read in
emniss_list <- c("emiss.d_core_Ref", "emiss.d_BYU_Ref", "emiss.d_core_Ctax_25_5", "emiss.d_BYU_Ctax_25_5")

emniss <- tibble()

for (s in emniss_list) {

  temp <- read.csv(paste0("gcam_data/", s, ".csv"))

  emniss %>%
    bind_rows(temp) -> emniss

  rm(temp)

}

emniss %>%
  gather(Year, value, -scenario, -region, -sector) %>%
  mutate(Year = gsub("X", "", Year)) %>%
  mutate(year = as.numeric(Year)) %>%
  select(-Year) %>%
  filter(year != 1975) %>%
  replace_na(list(value = 0)) -> CO2_emniss


# ============================================================================
# Mapping files

# Region Mappings
grid_mapping <- read.csv("mappings/grid_region_mapping.csv", comment.char = "#")
states_subregions <- read.csv("mappings/states_subregions.csv", comment.char = "#")

# Scenario Rename Mapping
# NOTE:  USER must add each new scenario to this mapping file
# If keeping the original scenario name, simply enter the
# same name in both the OG_scenario and scenario columns
scenario_mapping <- read.csv("mappings/scenario_rename_mapping.csv", skip = 1)

# Technology Mappings
elec_mapping <- read.csv("mappings/elec_tech_mapping.csv", comment.char = "#")
bldg_mapping <- read.csv("mappings/bldg_energy_mapping.csv", skip = 1)
indust_mapping <- read.csv("mappings/indust_energy_mapping.csv", skip = 1)
trans_mapping <- read.csv("mappings/transp_energy_mapping.csv", skip = 1)
FE_fuel_mapping <- read.csv("mappings/FE_fuel_mapping.csv", skip = 1)
FE_sector_mapping <- read.csv("mappings/FE_sector_mapping.csv", skip = 1)
liquids_mapping <- read.csv("mappings/refined_liquids_mapping.csv", skip = 1)
CO2_sector_mapping <- read.csv("mappings/CO2_mapping.csv", skip = 1)
CO2_mapping_EPA <- read.csv("mappings/CO2_mapping_EPA.csv", skip = 1)

trn_load_factors <- read.csv("outputs_core/L254.StubTranTechLoadFactor_USA.csv", comment.char = "#") %>%
  mutate(model = "Core") %>%
  bind_rows(read.csv("outputs_BYU/L254.StubTranTechLoadFactor_USA.csv", comment.char = "#") %>%
              mutate(model = "Base Year Update")) %>%
  filter(supplysector %in% c("trn_pass_road_LDV_4W", "trn_freight_road")) %>%
  distinct(model, supplysector, tranSubsector, year, loadFactor)

trn_sector_mapping <- read.csv("mappings/trn_agg_sector.csv", skip = 1)

# Historical data
EPA_CO2_emiss <- read_csv("data/epa_2015.csv", skip = 1)

# ============================================================================
# Conversions
source("scripts/constants.R")

CONV_EJ_TWh <- 1 / CONV_TWH_EJ
CONV_KM_MILE <- 0.621371

# ============================================================================
# Other helpful constants

PLOT_YEARS <- c(seq(from = 2010, to = 2100, by = 5))

FIGURE_DIMS <- list(dpi=300/2, width=3300/300, height=1860/300)

scenario_order <- c("Core_Ref", "BYU_Ref", "Core_Tax", "BYU_Tax")
model_order <- c("Core", "Base Year Update")
case_order <- c("Ref", "Tax")

elec_tech_order <- c("energy reduction", "Battery", "CHP", "Geothermal", "Solar",
                     "Offshore Wind", "Onshore Wind", "Hydro", "Nuclear", "Biomass w/ CCS", "Biomass w/o CCS",
                     "Coal w/ CCS", "Coal w/o CCS", "Gas w/ CCS", "Gas w/o CCS", "Oil w/ CCS", "Oil w/o CCS")

sector_order <- c("Building", "Industry", "Transportation", "Total")

scenario_palette <- c("GCAM-USA_Ref" = "green3", "GCAM-USA_BYU_Ref" = "dodgerblue2", "Historical" = "gray")
model_palette <- c("Core" = "green3", "Base Year Update" = "dodgerblue2")

scenario_lines <- c("GCAM-USA_Ref" = "solid", "GCAM-USA_BYU_Ref" = "dotted", "Historical" = "dashed")
model_lines <- c("Core" = "solid", "Base Year Update" = "dotted", "Historical" = "dashed")

sector_palette <- c("Transport" = "firebrick3", "Building" = "dodgerblue3", "Industry" = "springgreen4",
                    "Electricity" = "goldenrod", "Total" = "black", "Other" = "gray",
                    "Commercial"= "red", "Residential" = "blue",
                    "Freight Truck" = "firebrick3", "LDV" = "dodgerblue3")

# OPTIONAL: set output directory.
OUTPUT_DIR <- "figures/combined"

# ============================================================================
# Functions

# repeat_and_add_vector: function for repeating a dataframe in order to add a new vector
repeat_and_add_vector <- function( data, vector, vector_values ) {
  data_new <- data[ rep( 1:nrow( data ), times = length( vector_values ) ), ]
  data_new[[vector]] <- sort( rep( vector_values, length.out = nrow( data_new ) ) )
  return( data_new )
}


bar_plots <- function(fig_data, fill_var = "Fuel", color_pal, title, y_unit = "EJ", fig_path, plot_name,
                      xyears = c(2005, 2105), xbreaks = c(seq(2010, 2100, by = 10))) {

  for (r in unique(fig_data$region)){
    p <- ggplot() +
      geom_col(data=filter(fig_data, region == r),
               aes(x = year, y = value, fill = Fuel)) +
      scale_fill_manual(name = fill_var, values=color_pal) +
      facet_grid(case ~ model) +
      scale_x_continuous(limits = xyears, breaks=xbreaks) +
      # scale_x_continuous(breaks = c(seq(2010, 2100, 10))) +
      # scale_x_continuous(limits = c(2000, 2020), breaks=c(seq(2005, 2015, by = 5))) +
      # expand_limits(y = 0) +
      ggtitle( paste0(r, " - ", title)) +
      xlab("Year") +
      ylab(y_unit) +
      theme(panel.background = element_blank(),
            panel.grid.minor = element_blank(),
            panel.grid.major.x = element_line( size=.1, color="gray"),
            panel.grid.major.y = element_line( size=.1, color="gray"),
            plot.title = element_text(face="bold", size=18, hjust = 0.5),
            plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
            axis.title.x = element_text(margin = margin(t = 12), size = 16),
            axis.title.y = element_text(margin = margin(r = 12), size = 16),
            axis.text.x  = element_text(size=14, hjust = 1, vjust = 1, angle = 45),
            axis.text.y  = element_text(size=14),
            legend.title = element_text(size = 14),
            legend.text = element_text(size = 11),
            legend.key.height = unit(2, "line"),
            legend.key.width = unit(3, "line"),
            strip.text = element_text(size = 16, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
    ggsave(paste0(fig_path, r, plot_name, ".png"), dpi=300/2, width=3300/300, height=1860/300)
  }

}


line_plots <- function(fig_data, col_var = "Model", color_pal, title, y_unit = "EJ", fig_path, plot_name,
                       xyears = c(2005, 2105), xbreaks = c(seq(2010, 2100, by = 10)), facet_sector = F) {

  for (r in unique(fig_data$region)){
    if(facet_sector == T) {
      p <- ggplot() +
        geom_line(data = filter(fig_data, region == r),
                  aes(x = year, y = value, color = agg_sector, linetype = model), size = 1.5) +
        scale_color_manual(name = "Sector", values = sector_palette) +
        scale_linetype_manual(name = col_var, values = model_lines) +
        scale_x_continuous(limits = xyears, breaks=xbreaks) +
        # scale_x_continuous(breaks = c(seq(2010, 2100, 10))) +
        expand_limits(y = 0) +
        facet_wrap(. ~ case, ncol = 2) +
        ggtitle( paste0(r, " - ", title )) +
        xlab("Year") +
        ylab(y_unit) +
        theme(panel.background = element_blank(),
              panel.grid.minor = element_blank(),
              panel.grid.major.x = element_line( size=.1, color="gray"),
              panel.grid.major.y = element_line( size=.1, color="gray"),
              plot.title = element_text(face="bold", size=18, hjust = 0.5),
              plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
              axis.title.x = element_text(margin = margin(t = 12), size = 16),
              axis.title.y = element_text(margin = margin(r = 12), size = 16),
              axis.text.x  = element_text(size=14, hjust = 1, vjust = 1, angle = 45),
              axis.text.y  = element_text(size=14),
              legend.title = element_text(size = 14),
              legend.text = element_text(size = 11),
              legend.key.height = unit(2, "line"),
              legend.key.width = unit(3, "line"),
              strip.text = element_text(size = 10, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
      ggsave(paste0(fig_path, r, plot_name, ".png"), dpi=300/2, width=3300/300, height=1860/300)
    } else {
      p <- ggplot() +
        geom_line(data=filter(fig_data, region == r),
                  aes(x = year, y = value, color = model), size = 1.5) +
        scale_color_manual(name = "Model", values = color_pal) +
        scale_x_continuous(breaks=c(seq(2010, 2100, 10))) +
        expand_limits(y = 0) +
        facet_wrap(. ~ case, ncol = 2) +
        ggtitle( paste0(r, " - ", title )) +
        xlab("Year") +
        ylab(y_unit) +
        theme(panel.background = element_blank(),
              panel.grid.minor = element_blank(),
              panel.grid.major.x = element_line( size=.1, color="gray"),
              panel.grid.major.y = element_line( size=.1, color="gray"),
              plot.title = element_text(face="bold", size=18, hjust = 0.5),
              plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
              axis.title.x = element_text(margin = margin(t = 12), size = 16),
              axis.title.y = element_text(margin = margin(r = 12), size = 16),
              axis.text.x  = element_text(size=14, hjust = 1, vjust = 1, angle = 45),
              axis.text.y  = element_text(size=14),
              legend.title = element_text(size = 14),
              legend.text = element_text(size = 11),
              legend.key.height = unit(2, "line"),
              legend.key.width = unit(3, "line"),
              strip.text = element_text(size = 10, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
      ggsave(paste0(fig_path, r, plot_name, ".png"), dpi=300/2, width=3300/300, height=1860/300)
    }
  }
}


# calc_diff <- function(data, grouping_vars) {
#
#   data %>%
#     group_by(grouping_vars) %>%
#     mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
#     ungroup() %>%
#     select(-value) %>%
#     rename(value = DIFF)
#
# }


# ============================================================================
# Generate graphs

printlog( "-------- Plotting --------" )

# ============================================================================
# Electricity Generation

printlog( "Primary Energy" )

PE <- getQuery(prj, 'primary energy consumption by region (direct equivalent)')

PE %>%
  filter(year %in% PLOT_YEARS) %>%
  rename(Fuel = fuel) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(scenario = factor(scenario, levels = scenario_order),
         model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> PE_USA

bar_plots(fig_data = PE_USA, fill_var = "Fuel", color_pal = PAL_pri_ene,
          title = "Primary Energy", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_PE")

# Diff plot
PE_USA %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> PE_USA_DIFF

bar_plots(fig_data = PE_USA_DIFF, fill_var = "Fuel", color_pal = PAL_pri_ene,
          title = "Primary Energy - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_PE_DIFF")

# Total PE change
PE_USA %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  group_by(scenario, model, case, year, Units) %>%
  summarise(PE = sum(value),
            TOT_DIFF = sum(DIFF),
            PCT_DIF = TOT_DIFF / PE) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> PE_USA_DIFF_TOTAL

# ============================================================================
# Electricity Generation

printlog( "Electricity Generation by Technology" )

elec_gen <- getQuery(prj, 'elec gen by gen tech')

elec_gen %>%
  filter(year %in% PLOT_YEARS) %>%
  mutate(value = value * CONV_EJ_TWh) %>%
  mutate(Units = "TWh") %>%
  left_join_error_no_match(elec_mapping, by = c("technology")) %>%
  filter(aggregate_tech != "DROP") %>%
  mutate(aggregate_tech =  factor(aggregate_tech, levels = elec_tech_order)) %>%
  rename(Fuel = aggregate_tech) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(scenario = factor(scenario, levels = scenario_order),
         model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> elec_gen_state

# Plot state totals
bar_plots(fig_data = elec_gen_state, fill_var = "Technology", color_pal = elec_tech_colors,
          title = "Electricity Generation by Technology", y_unit = "Twh",
          fig_path = "figures/elec_gen_tech/",
          plot_name = "_elec_gen_fuel")

# Plot grid totals
elec_gen_state %>%
  left_join_error_no_match(grid_mapping, by = c("region")) %>%
  mutate(grid_region = as.character(grid_region)) %>%
  group_by(grid_region, scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  rename(region = grid_region) -> elec_gen_grid

bar_plots(fig_data = elec_gen_grid, fill_var = "Technology", color_pal = elec_tech_colors,
          title = "Electricity Generation by Technology", y_unit = "Twh",
          fig_path = "figures/grid_elec_gen/",
          plot_name = "_elec_gen_fuel")

# Plot USA totals
elec_gen_grid %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> elec_gen_USA

bar_plots(fig_data = elec_gen_USA, fill_var = "Technology", color_pal = elec_tech_colors,
          title = "Electricity Generation by Technology", y_unit = "Twh",
          fig_path = "figures/",
          plot_name = "_elec_gen_fuel")

# Diff plot - Grid
elec_fuels <- unique(elec_gen_state$Fuel)

elec_gen_grid %>%
  select(-scenario) %>%
  complete(nesting(region, model, case, year, Units), Fuel = elec_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> elec_gen_grid_DIFF

bar_plots(fig_data = elec_gen_grid_DIFF, fill_var = "Technology", color_pal = elec_tech_colors,
          title = "Electricity Generation by Technology - Change from Core", y_unit = "Twh (Base Year Update minus Core)",
          fig_path = "figures/grid_elec_gen/",
          plot_name = "_elec_gen_fuel_DIFF")

# Diff plot - USA
elec_gen_USA %>%
  select(-scenario) %>%
  complete(nesting(region, model, case, year, Units), Fuel = elec_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> elec_gen_USA_DIFF

bar_plots(fig_data = elec_gen_USA_DIFF, fill_var = "Technology", color_pal = elec_tech_colors,
          title = "Electricity Generation by Technology - Change from Core", y_unit = "Twh (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_elec_gen_fuel_DIFF")

# Total elec change
elec_gen_USA %>%
  group_by(model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  group_by(case, year, Units) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"],
         PCT_DIF = DIFF / value) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> elec_gen_USA_DIFF_TOTAL


# ============================================================================
# Final Energy Consumption by sector and state

printlog( "Final Energy Consumption" )

# FE <- getQuery(prj, 'total final energy by sector')
FE_bld <- getQuery(prj, 'building final energy by tech')
FE_ind <- getQuery(prj, 'industry final energy by tech and fuel')
FE_trn <- getQuery(prj, 'transport final energy by tech and fuel') %>% rename(subsector = mode)

FE_bld %>%
  bind_rows(FE_ind, FE_trn) -> FE

FE %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(FE_fuel_mapping, by = c("input")) %>%
  left_join_error_no_match(FE_sector_mapping, by = c("sector")) %>%
  # filtering out industrial processes
  filter(input != "industrial processes") %>%
  group_by(scenario, region, year, Units, agg_sector, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(scenario = factor(scenario, levels = scenario_order),
         model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> FE_cons

# Add state total
FE_cons %>%
  group_by(scenario, model, case, region, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(agg_sector = "Total") -> FE_cons_total

FE_cons %>%
  bind_rows(FE_cons_total) %>%
  mutate(country = "USA") %>%
  mutate(country = as.character(country)) %>%
  mutate(agg_sector =  factor(agg_sector, levels = sector_order)) %>%
  mutate(scenario = factor(scenario, levels = scenario_order)) %>%
  arrange(agg_sector) -> FE_cons

# Plot state totals
for (state in unique(FE_cons$region)){
  p <- ggplot() +
    geom_col(data=filter(FE_cons, region == state),
             aes(x = year, y = value, fill=Fuel)) +
    scale_fill_manual(values=enduse_colors_AEO) +
    facet_grid(agg_sector ~ scenario) +
    scale_x_continuous(limits = c(2005, 2105), breaks=c(seq(2010, 2100, by = 10))) +
    # expand_limits(y = 0) +
    ggtitle( paste0(state, " - Final Energy Consumption by Sector" )) +
    xlab("Year") +
    ylab("EJ") +
    theme(panel.background = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major.x = element_line( size=.1, color="gray"),
          panel.grid.major.y = element_line( size=.1, color="gray"),
          plot.title = element_text(face="bold", size=18, hjust = 0.5),
          plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
          axis.title.x = element_text(margin = margin(t = 12), size = 16),
          axis.title.y = element_text(margin = margin(r = 12), size = 16),
          axis.text.x  = element_text(size=14, hjust = 1, vjust = 1, angle = 45),
          axis.text.y  = element_text(size=14),
          legend.title = element_text(size = 14),
          legend.text = element_text(size = 11),
          legend.key.height = unit(2, "line"),
          legend.key.width = unit(3, "line"),
          strip.text = element_text(size = 10, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
  ggsave(paste0("figures/FE_sector_fuel/", state,"_FE_sector_fuel.png"), dpi=300/2, width=3300/300, height=1860/300)
}

# Plot USA totals
p <- ggplot() +
  geom_col(data=FE_cons, aes(x = year, y = value, fill=Fuel)) +
  scale_fill_manual(values=enduse_colors_AEO) +
  facet_grid(agg_sector ~ scenario) +
  scale_x_continuous(limits = c(2005, 2105), breaks=c(seq(2010, 2100, by = 10))) +
  # expand_limits(y = 0) +
  ggtitle( paste0("USA", " - Final Energy Consumption by Sector" )) +
  xlab("Year") +
  ylab("EJ") +
  theme(panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_line( size=.1, color="gray"),
        panel.grid.major.y = element_line( size=.1, color="gray"),
        plot.title = element_text(face="bold", size=18, hjust = 0.5),
        plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
        axis.title.x = element_text(margin = margin(t = 12), size = 16),
        axis.title.y = element_text(margin = margin(r = 12), size = 16),
        axis.text.x  = element_text(size=14, hjust = 1, vjust = 1, angle = 45),
        axis.text.y  = element_text(size=14),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 11),
        legend.key.height = unit(2, "line"),
        legend.key.width = unit(3, "line"),
        strip.text = element_text(size = 10, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
ggsave(paste0("figures/FE_sector_fuel/", "USA", "_FE_sector_fuel.png"), dpi=300/2, width=3300/300, height=1860/300)


# ============================================================================
# Building Energy Consumption

printlog( "Final Energy Consumption: Buildings" )

bld_FE <- getQuery(prj, 'building final energy by tech')

bld_FE %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(bldg_mapping, by = c("input")) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> building_energy

bar_plots(fig_data = building_energy, fill_var = "Fuel", color_pal = building_colors,
          title = "Final Energy Consumption: Buildings", y_unit = "EJ",
          fig_path = "figures/building_FE/",
          plot_name = "_building_FE")

# bar_plots(fig_data = building_energy, fill_var = "Fuel", color_pal = building_colors,
#           title = "Final Energy Consumption: Buildings", y_unit = "EJ",
#           fig_path = "figures/building_FE/hist/",
#           plot_name = "_building_FE",
#           xyears = c(2000, 2020), xbreaks = c(seq(2005, 2015, 5)))

# Plot USA totals
building_energy %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> building_energy_USA

bar_plots(fig_data = building_energy_USA, fill_var = "Fuel", color_pal = building_colors,
          title = "Final Energy Consumption: Buildings", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_building_FE")

# Diff plot - States
# bld_fuels <- unique(building_energy$Fuel)
#
# building_energy %>%
#   group_by(region, model, case, year, Units, Fuel) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() %>%
#   complete(nesting(region, model, case, year, Units), Fuel = bld_fuels) %>%
#   replace_na(list(value = 0)) %>%
#   group_by(region, case, year, Units, Fuel) %>%
#   mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
#   ungroup() %>%
#   filter(model == "Base Year Update") %>%
#   select(-value) %>%
#   rename(value = DIFF) -> building_energy_DIFF
#
# bar_plots(fig_data = building_energy_DIFF, fill_var = "Fuel", color_pal = building_colors,
#           title = "Final Energy Consumption: Buildings - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
#           fig_path = "figures/building_FE/",
#           plot_name = "_building_FE_DIFF")

# Diff plot - USA
bld_fuels <- unique(building_energy_USA$Fuel)

building_energy_USA %>%
  complete(nesting(region, model, case, year, Units), Fuel = bld_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> building_energy_USA_DIFF

bar_plots(fig_data = building_energy_USA_DIFF, fill_var = "Fuel", color_pal = building_colors,
          title = "Final Energy Consumption: Buildings - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_building_FE_DIFF")


# ============================================================================
# Industry Energy Consumption

printlog( "Final Energy Consumption: Industry" )

ind_FE <- getQuery(prj, 'industry final energy by tech and fuel')

ind_FE %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(indust_mapping, by = c("input")) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> indust_energy

bar_plots(fig_data = indust_energy, fill_var = "Fuel", color_pal = indust_colors,
          title = "Final Energy Consumption: Industry", y_unit = "EJ",
          fig_path = "figures/industry_FE/",
          plot_name = "_industry_FE")

# Plot USA totals
indust_energy %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> indust_energy_USA

bar_plots(fig_data = indust_energy_USA, fill_var = "Fuel", color_pal = indust_colors,
          title = "Final Energy Consumption: Industry", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_industry_FE")

# Diff plot - USA
ind_fuels <- unique(indust_energy_USA$Fuel)

indust_energy_USA %>%
  complete(nesting(region, model, case, year, Units), Fuel = ind_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> indust_energy_USA_DIFF

bar_plots(fig_data = indust_energy_USA_DIFF, fill_var = "Fuel", color_pal = indust_colors,
          title = "Final Energy Consumption: Industry - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_industry_FE_DIFF")

# Total ind FE change
indust_energy_USA %>%
  group_by(model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  group_by(case, year, Units) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"],
         PCT_DIF = DIFF / value) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> indust_energy_USA_DIFF_TOTAL

# Ind FE shares
indust_energy_USA %>%
  group_by(model, case, year, Units) %>%
  mutate(total = sum(value),
         share = value / total) %>%
  ungroup() %>%
  # select(-scenario, -value, -total) %>%
  # spread(model, share) %>%
  group_by(case, year, Fuel, Units) %>%
  mutate(share_DIFF = share[model=="Base Year Update"] - share[model=="Core"]) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> indust_energy_USA_share

# Ind FE by sector (feedstocks)
ind_FE %>%
  # filter(year %in% PLOT_YEARS,
  filter(year %in% c(2005, 2010, 2015),
         sector == "industrial feedstocks") %>%
  left_join_error_no_match(indust_mapping, by = c("input")) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> indust_energy_sector

bar_plots(fig_data = indust_energy_sector, fill_var = "Fuel", color_pal = indust_colors,
          title = "Final Energy Consumption: Industrial Feedstocks", y_unit = "EJ",
          fig_path = "figures/industry_FE/feedstocks/",
          plot_name = "_ind_feedstock_FE",
          xyears = c(2000, 2020), xbreaks = c(seq(2005, 2015, 5)))

# Plot USA totals
indust_energy_sector %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> indust_energy_sector_USA

bar_plots(fig_data = indust_energy_sector_USA, fill_var = "Fuel", color_pal = indust_colors,
          title = "Final Energy Consumption: Industry", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_ind_feedstocks_FE",
          xyears = c(2000, 2020), xbreaks = c(seq(2005, 2015, 5)))
  
# ============================================================================
# Transportation Energy Consumption

printlog( "Final Energy Consumption: Transportation" )

trn_FE <- getQuery(prj, 'transport final energy by tech and fuel')

trn_FE %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(trans_mapping, by = c("input"))  %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> trans_energy

bar_plots(fig_data = trans_energy, fill_var = "Fuel", color_pal = trn_fuel_colors,
          title = "Final Energy Consumption: Transportation", y_unit = "EJ",
          fig_path = "figures/transport_FE/",
          plot_name = "_transport_FE")

# Plot USA totals
trans_energy %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> trans_energy_USA

bar_plots(fig_data = trans_energy_USA, fill_var = "Fuel", color_pal = trn_fuel_colors,
          title = "Final Energy Consumption: Transportation", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_transport_FE")

# Diff plot - USA
trn_fuels <- unique(trans_energy_USA$Fuel)

trans_energy_USA %>%
  complete(nesting(region, model, case, year, Units), Fuel = trn_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> trans_energy_USA_DIFF

bar_plots(fig_data = trans_energy_USA_DIFF, fill_var = "Fuel", color_pal = trn_fuel_colors,
          title = "Final Energy Consumption: Transportation - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_transport_FE_DIFF")

# Change in total trn FE
trans_energy_USA %>%
  complete(nesting(region, model, case, year, Units), Fuel = trn_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  group_by(case, year, Units) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"],
         PCT_DIF = DIFF / value) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> trans_energy_USA_DIFF_TOTAL


# ============================================================================
# Refined Liquids by Fuel

printlog( "Refined Liquids by Fuel" )

RL_prod <- getQuery(prj, 'refined liquids production by tech')

RL_prod %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(liquids_mapping, by = c("technology")) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> refined_liquids

bar_plots(fig_data = refined_liquids, fill_var = "Fuel", color_pal = liquids_fuel_colors,
          title = "Refined Liquids Production", y_unit = "EJ",
          fig_path = "figures/refining/",
          plot_name = "_liquids_prod")

# Plot USA totals
refined_liquids %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> refined_liquids_USA

bar_plots(fig_data = refined_liquids_USA, fill_var = "Fuel", color_pal = liquids_fuel_colors,
          title = "Refined Liquids Production", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_liquids_prod")

# Diff plot - USA
RL_fuels <- unique(refined_liquids_USA$Fuel)

refined_liquids_USA %>%
  complete(nesting(region, model, case, year, Units), Fuel = RL_fuels) %>%
  replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> refined_liquids_USA_DIFF

bar_plots(fig_data = refined_liquids_USA_DIFF, fill_var = "Fuel", color_pal = liquids_fuel_colors,
          title = "Refined Liquids Production - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_liquids_prod_DIFF")

# Total RL change
refined_liquids_USA %>%
  group_by(model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  group_by(case, year, Units) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"],
         PCT_DIF = DIFF / value) %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> refined_liquids_USA_DIFF_TOTAL

# Total RL
refined_liquids %>%
  group_by(model, case, region, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  ungroup() -> refined_liquids_state_total

# ============================================================================
# Biomass consumption

printlog( "Biomass consumption" )

en_cons <- getQuery(prj, 'inputs by tech')

bio_inputs <- c("regional biomass", "regional biomassOil", "regional corn for ethanol", "regional sugar for ethanol",
                "delivered biomass")

bio_input_order <- c("TOTAL", "regional biomass", "delivered biomass", "regional biomassOil",
                     "regional corn for ethanol", "regional sugar for ethanol")

en_cons %>%
  filter(year %in% PLOT_YEARS,
         input %in% bio_inputs,
         !(input == "regional biomass" & sector == "delivered biomass"),
         !(input == "regional biomass" & sector == "regional biomass")) %>%
  group_by(scenario, region, input, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() -> bio_cons

# # Add total
# bio_cons %>%
#   group_by(scenario, region, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() %>%
#   mutate(input = "TOTAL") -> bio_cons_total

bio_cons %>%
  # bind_rows(bio_cons_total) %>%
  rename(Fuel = input) %>%
  mutate(Fuel = factor(Fuel, levels = bio_input_order)) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> bio_cons

# for (state in unique(bio_cons$region)){
#   p <- ggplot() +
#     geom_line(data=filter(bio_cons, region == state),
#               aes(x = year, y = value, linetype = scenario, color = input), size = 1.5) +
#     scale_linetype_manual(name = "Scenario", values=scenario_lines) +
#     facet_wrap(. ~ input, ncol=3) +
#     scale_x_continuous(breaks=c(seq(2010, 2100, 10))) +
#     # expand_limits(y = 0) +
#     ggtitle( paste0(state, " - Biomass Consumption" )) +
#     xlab("Year") +
#     ylab("EJ") +
#     theme(panel.background = element_blank(),
#           panel.grid.minor = element_blank(),
#           panel.grid.major.x = element_line( size=.1, color="gray"),
#           panel.grid.major.y = element_line( size=.1, color="gray"),
#           plot.title = element_text(face="bold", size=18, hjust = 0.5),
#           plot.margin = unit(c(0.75, 0.75, 0.75, 0.75), "cm"),
#           axis.title.x = element_text(margin = margin(t = 12), size = 16),
#           axis.title.y = element_text(margin = margin(r = 12), size = 16),
#           axis.text.x  = element_text(size=10, hjust = 1, vjust = 1, angle = 45),
#           axis.text.y  = element_text(size=10),
#           legend.title = element_text(size = 14),
#           legend.text = element_text(size = 11),
#           legend.key.height = unit(2, "line"),
#           legend.key.width = unit(3, "line"),
#           strip.text = element_text(size = 12, face = "bold", margin = margin(0,0.3,0,0.3, "cm")))
#   ggsave(paste0("figures/bio_consumption/", state,"_biomass_cons.png"), dpi=300/2, width=3300/300, height=1860/300)
# }

bio_colors <- c( "delivered biomass" = "#d01c2a",
                 "regional biomass" = "#25a9e0",
                 "regional biomassOil" = "#a0237c",
                 "regional corn for ethanol" = "#00931d",
                 "TOTAL" = "grey")

bar_plots(fig_data = bio_cons, fill_var = "Input", color_pal = bio_colors,
          title = "Biomass Consumption", y_unit = "EJ",
          fig_path = "figures/bio_consumption/",
          plot_name = "_biomass_cons")

# Plot USA totals
bio_cons %>%
  group_by(scenario, model, case, year, Units, Fuel) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> bio_cons_USA

bar_plots(fig_data = bio_cons_USA, fill_var = "Input", color_pal = bio_colors,
          title = "Biomass Consumption", y_unit = "EJ",
          fig_path = "figures/",
          plot_name = "_biomass_cons")

# Diff plot - USA
# bio_fuels <- unique(bio_cons_USA$Fuel)

bio_cons_USA %>%
  # complete(nesting(region, model, case, year, Units), Fuel = bio_fuels) %>%
  # replace_na(list(value = 0)) %>%
  group_by(region, case, year, Units, Fuel) %>%
  mutate(DIFF = value[model=="Base Year Update"] - value[model=="Core"]) %>%
  ungroup() %>%
  filter(model == "Base Year Update") %>%
  select(-value) %>%
  rename(value = DIFF) -> bio_cons_USA_DIFF

bar_plots(fig_data = bio_cons_USA_DIFF, fill_var = "Input", color_pal = bio_colors,
          title = "Biomass Consumption - Change from Core", y_unit = "EJ (Base Year Update minus Core)",
          fig_path = "figures/",
          plot_name = "_biomass_cons_DIFF")


# ============================================================================
# CO2 emissions by sector

printlog( "CO2 emissions by sector" )

CO2_emniss %>%
  filter(year %in% PLOT_YEARS) %>%
  left_join_error_no_match(CO2_sector_mapping, by = c("sector")) %>%
  group_by(scenario, region, year, agg_sector) %>%
  summarise(value = sum(value) * emissions.CONV_C_CO2) %>%
  mutate(Units = "MTCO2") %>%
  ungroup() %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> CO2

# Add total for GCAM
CO2 %>%
  group_by(scenario, model, case, region, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(agg_sector = "Total") -> CO2_total

# # Check no bio emissions total to direct query results
# CO2_tech <- getQuery(prj, 'CO2 emissions by tech') %>%
#   filter(year %in% PLOT_YEARS) %>%
#   rename(OG_scenario = scenario) %>%
#   left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
#   select(-OG_scenario) %>%
#   mutate(model = factor(model, levels = model_order),
#          case = factor(case, levels = case_order)) %>%
#   # group_by(scenario, region, year) %>%
#   group_by(scenario, year) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() %>%
#   mutate(value = value * emissions.CONV_C_CO2,
#          Units = "MTCO2")
#
# CO2_total %>%
#   group_by(scenario, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() %>%
#   rename(emNiss = value) %>%
#   left_join_error_no_match(CO2_tech %>%
#                              rename(emiss = value),
#                            by = c("scenario", "year", "Units")) %>%
#   mutate(DIFF = (emNiss - emiss) / emiss) -> CO2_TEST
#
# stopifnot(CO2_TEST$DIFF < 0.001)

EPA_CO2_emiss %>%
  gather_years() %>%
  mutate(year = as.integer(year)) %>%
  left_join(states_subregions %>%
              select(state, state_name),
            by = c("State" = "state_name")) %>%
  left_join_error_no_match(CO2_mapping_EPA, by = "Sector") %>%
  select(-State, -Sector) %>%
  rename(region = state) %>%
  group_by(region, agg_sector, year) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(Units = "MTCO2",
         scenario = "Historical",
         model = "Historical",
         case = "Ref") -> CO2_hist

CO2 %>%
  bind_rows(CO2_total, CO2_hist) -> CO2

# Plot state totals
line_plots(fig_data = CO2, color_pal = model_palette,
           title = "Energy System CO2 Emissions", y_unit = "MTCO2",
           fig_path = "figures/CO2_sector/", plot_name = "_CO2_sector",
           facet_sector = T)

# USA total
CO2 %>%
  group_by(scenario, model, case, year, Units, agg_sector) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> CO2_USA

line_plots(fig_data = CO2_USA, color_pal = model_palette,
           title = "Energy System CO2 Emissions", y_unit = "MTCO2",
           fig_path = "figures/", plot_name = "_CO2_sector",
           facet_sector = T)

# Near term CO2 scatterplots
plot_scatter <- function(line_data, criteria_min, criteria_max,
                         plot_data, x_var, y_var,
                         limits_x, limits_y, breaks_xy,
                         x_label, y_label, title, plot_name){

  # Plot
  p <- ggplot() + geom_line(data=line_data, aes(x=x, y=y)) +
    geom_ribbon(data=line_data, aes(x=x, ymin = criteria_min, ymax = criteria_max), alpha = 0.25, fill = "green") +
    geom_text(data=plot_data, aes(x=x_var, y=y_var, label=region)) +
    scale_x_continuous(limits = limits_x, breaks=breaks_xy) +
    scale_y_continuous(limits = limits_y, breaks=breaks_xy) +
    facet_grid(agg_sector ~ year) +
    ggtitle(title) +
    theme(plot.title = element_text(face="bold", size=14, hjust = 0.5)) +
    xlab(x_label) +
    ylab(y_label) +
    theme(panel.background = element_blank(),
          panel.grid.minor = element_blank(),
          panel.grid.major.x = element_line( size=.1, color="gray"),
          panel.grid.major.y = element_line( size=.1, color="gray"),
          axis.title.x = element_text(size=14),
          axis.text.x  = element_text(size=12, vjust = 0),
          axis.title.y = element_text(size=14),
          axis.text.y  = element_text(size=12),
          strip.text = element_text(size=16))
  ggsave(paste0("figures/",  plot_name, ".png"), dpi=600/2, width=3000/300, height=3000/300)

}

CO2_sectors <- c("Total", "Building", "Industry", "Transport", "Electricity")

scatter_line <- data.frame('x'= c(seq(0, 1000, by = 10))) %>%
  mutate(y = x) %>%
  # repeat_and_add_vector("scenario", c("Historical", "GCAM_USA")) %>%
  repeat_and_add_vector("agg_sector", CO2_sectors) %>%
  repeat_and_add_vector("year", c(2010, 2015))

# ALL
CO2_scatter <- CO2 %>%
  filter(model %in% c("Base Year Update", "Historical"),
         case == "Ref",
         year %in% c(2010, 2015),
         region != "USA") %>%
  select(-model, -case) %>%
  spread(scenario, value) %>%
  rename(GCAM_USA = BYU_Ref) %>%
  mutate(GCAM_USA = ifelse(GCAM_USA < 0, 0, GCAM_USA))

plot_scatter(line_data = scatter_line,
             criteria_min = scatter_line$y * 0.9,
             criteria_max = scatter_line$y * 1.1,
             plot_data = CO2_scatter,
             x_var = CO2_scatter$Historical,
             y_var = CO2_scatter$GCAM_USA,
             limits_x = c(0, 800),
             limits_y = c(0, 800),
             breaks_xy = c(seq(0, 800, by = 100)),
             x_label = "History (MTCO2)",
             y_label = "GCAM-USA Base Year Update",
             title = "CO2 Emissions - Historical Comparison",
             plot_name = "CO2_history/CO2_scatter_full")

# High emissions
CO2_scatter_high <- CO2_scatter %>%
  group_by(region) %>%
  filter(!(Historical > 250 | GCAM_USA > 250)) %>%
  ungroup()

plot_scatter(line_data = scatter_line,
             criteria_min = scatter_line$y * 0.9,
             criteria_max = scatter_line$y * 1.1,
             plot_data = CO2_scatter_high,
             x_var = CO2_scatter_high$Historical,
             y_var = CO2_scatter_high$GCAM_USA,
             limits_x = c(0, 300),
             limits_y = c(0, 300),
             breaks_xy = c(seq(0, 250, by = 50)),
             x_label = "History (MTCO2)",
             y_label = "GCAM-USA Base Year Update",
             title = "CO2 Emissions - Historical Comparison",
             plot_name = "CO2_history/CO2_scatter_high")

# Medium emissions
CO2_scatter_med <- CO2_scatter %>%
  group_by(region) %>%
  filter(!(Historical > 125 | GCAM_USA > 125)) %>%
  ungroup()

plot_scatter(line_data = scatter_line,
             criteria_min = scatter_line$y * 0.9,
             criteria_max = scatter_line$y * 1.1,
             plot_data = CO2_scatter_med,
             x_var = CO2_scatter_med$Historical,
             y_var = CO2_scatter_med$GCAM_USA,
             limits_x = c(0, 150),
             limits_y = c(0, 150),
             breaks_xy = c(seq(0, 125, by = 25)),
             x_label = "History (MTCO2)",
             y_label = "GCAM-USA Base Year Update",
             title = "CO2 Emissions - Historical Comparison",
             plot_name = "CO2_history/CO2_scatter_med")


# Medium emissions
CO2_scatter_low <- CO2_scatter %>%
  group_by(region) %>%
  filter(!(Historical > 50 | GCAM_USA > 50)) %>%
  ungroup()

plot_scatter(line_data = scatter_line,
             criteria_min = scatter_line$y * 0.9,
             criteria_max = scatter_line$y * 1.1,
             plot_data = CO2_scatter_low,
             x_var = CO2_scatter_low$Historical,
             y_var = CO2_scatter_low$GCAM_USA,
             limits_x = c(0, 60),
             limits_y = c(0, 60),
             breaks_xy = c(seq(0, 50, by = 10)),
             x_label = "History (MTCO2)",
             y_label = "GCAM-USA Base Year Update",
             title = "CO2 Emissions - Historical Comparison",
             plot_name = "CO2_history/CO2_scatter_low")


# outliers
CO2_scatter_outliers <- CO2_scatter %>%
  group_by(region) %>%
  filter(GCAM_USA < (Historical * 0.9) | GCAM_USA > (Historical * 1.1)) %>%
  ungroup()

plot_scatter(line_data = scatter_line,
             criteria_min = scatter_line$y * 0.9,
             criteria_max = scatter_line$y * 1.1,
             plot_data = CO2_scatter_outliers,
             x_var = CO2_scatter_outliers$Historical,
             y_var = CO2_scatter_outliers$GCAM_USA,
             limits_x = c(0, 800),
             limits_y = c(0, 800),
             breaks_xy = c(seq(0, 800, by = 100)),
             x_label = "History (MTCO2)",
             y_label = "GCAM-USA Base Year Update",
             title = "CO2 Emissions - Historical Comparison",
             plot_name = "CO2_history/CO2_scatter_outliers")

write.csv(CO2_scatter_outliers, "CO2_outliers_BYU.csv",row.names = F)
# write.csv(CO2_scatter_outliers %>% filter(year == 2015), "CO2_outliers_BYU.csv",row.names = F)

CO2_core_outliers <- CO2 %>%
  filter(model %in% c("Core", "Historical"),
         case == "Ref",
         year %in% c(2010, 2015),
         # year == 2015,
         region != "USA") %>%
  select(-model, -case) %>%
  spread(scenario, value) %>%
  rename(GCAM_USA = Core_Ref) %>%
  mutate(GCAM_USA = ifelse(GCAM_USA < 0, 0, GCAM_USA)) %>%
  filter(GCAM_USA < (Historical * 0.9) | GCAM_USA > (Historical * 1.1))

write.csv(CO2_core_outliers, "CO2_outliers_Core.csv",row.names = F)

# ============================================================================
# Population

printlog( "Population" )

# GCAM
pop <- getQuery(prj, 'population by region')

pop %>%
  filter(year >= 2010,
         year <= 2100) %>%
  group_by(scenario, region, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(value = value / 1000,
         Units = "millions") %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) %>%
  filter(case == "Ref") -> pop_state

# Plot state totals
line_plots(fig_data = pop_state, color_pal = model_palette,
           title = "Population", y_unit = "Population (millions)",
           fig_path = "figures/population/", plot_name = "_pop")

# Plot USA totals
pop_state %>%
  group_by(scenario, model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> pop_USA

line_plots(fig_data = pop_USA, color_pal = model_palette,
           title = "Population", y_unit = "Population (millions)",
           fig_path = "figures/", plot_name = "_pop")


# ============================================================================
# GDP

printlog( "GDP" )

# GCAM
GDP <- getQuery(prj, 'GDP MER by region')

GDP %>%
  filter(year >= 2010,
         year <= 2100) %>%
  group_by(scenario, region, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(value = value * gdp_deflator(2015, 1990) / 1000,
         Units = "billion 2015 USD") %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) %>%
  filter(case == "Ref") -> GDP_GCAM_state

# Plot state totals
line_plots(fig_data = GDP_GCAM_state, color_pal = model_palette,
           title = "GDP", y_unit = "GDP (billion 2015 USD)",
           fig_path = "figures/GDP/", plot_name = "_GDP")

# Plot USA totals
GDP_GCAM_state %>%
  group_by(scenario, model, case, year, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> GDP_GCAM_USA

line_plots(fig_data = GDP_GCAM_USA, color_pal = model_palette,
           title = "GDP", y_unit = "GDP (billion 2015 USD)",
           fig_path = "figures/", plot_name = "_GDP")


# ============================================================================
# Floorspace

printlog( "Floorspace" )

# GCAM
flspc <- getQuery(prj, 'building floorspace')

flspc %>%
  filter(year %in% PLOT_YEARS) %>%
  mutate(agg_sector = if_else(building == "comm", "Commercial", "Residential")) %>%
  select(scenario, region, year, agg_sector, Units, value) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) -> floorspace

# Plot state totals
line_plots(fig_data = floorspace, color_pal = model_palette,
           title = "Floorspace", y_unit = "Floorspace (billion m^2)",
           fig_path = "figures/floorspace/", plot_name = "_floorspace",
           facet_sector = T)

# line_plots(fig_data = floorspace, color_pal = model_palette,
#            title = "Floorspace", y_unit = "Floorspace (billion m^2)",
#            fig_path = "figures/floorspace/hist/", plot_name = "_floorspace",
#            xyears = c(2005, 2015), xbreaks = c(seq(2005, 2015, 5)),
#            facet_sector = T)

# USA total
floorspace %>%
  group_by(scenario, model, case, year, agg_sector, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> floorspace_USA

line_plots(fig_data = floorspace_USA, color_pal = model_palette,
           title = "Floorspace", y_unit = "Floorspace (billion m^2)",
           fig_path = "figures/", plot_name = "_floorspace",
           facet_sector = T)


# ============================================================================
# VMT

printlog( "Vehicle Miles Traveled" )

# GCAM
trn_service <- getQuery(prj, 'transport service output by mode')

trn_service %>%
  filter(year %in% PLOT_YEARS) %>%
  rename(OG_scenario = scenario) %>%
  left_join_error_no_match(scenario_mapping, by = "OG_scenario") %>%
  select(-OG_scenario) %>%
  mutate(model = factor(model, levels = model_order),
         case = factor(case, levels = case_order)) %>%
  semi_join(trn_load_factors,
            by = c("sector" = "supplysector", "mode" = "tranSubsector")) %>%
  left_join_error_no_match(trn_load_factors %>%
                             rename(mode = tranSubsector),
                           by = c("model", "sector" = "supplysector", "mode", "year")) %>%
  filter(!is.na(loadFactor)) %>%
  mutate(value = value / loadFactor * CONV_KM_MILE / 1000,
         Units = "billion vehicle miles") %>%
  left_join_error_no_match(trn_sector_mapping %>%
                             rename(mode = subsector),
                           by = c("sector", "mode")) %>%
  group_by(scenario, model, case, region, year, agg_sector, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() -> VMT

# vmt_palette <- c("Freight Truck" = "firebrick3", "LDV" = "dodgerblue3")

# Plot state totals
line_plots(fig_data = VMT, color_pal = model_palette,
           title = "Vehicle Miles Traveled", y_unit = "VMT (billion vehicle miles)",
           fig_path = "figures/VMT/", plot_name = "_VMT",
           facet_sector = T)

# USA total
VMT %>%
  group_by(scenario, model, case, year, agg_sector, Units) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "USA") -> VMT_USA

line_plots(fig_data = VMT_USA, color_pal = model_palette,
           title = "Vehicle Miles Traveled", y_unit = "VMT (billion vehicle miles)",
           fig_path = "figures/", plot_name = "_VMT",
           facet_sector = T)

# # Testing
# trn_service %>%
#   filter(grepl("freight", sector)) %>%
#   group_by(scenario, sector, mode, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() -> freight_tonkm_mode
# 
# freight_tonkm_mode %>%
#   group_by(scenario, sector, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() -> freight_tonkm
# 
# freight_tonkm_mode %>%
#   filter(sector == "trn_freight_road") %>%
#   group_by(scenario, sector, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup() -> freight_tonkm_road


# ============================================================================
# Make sure negative emissions budget is working

# prj2 <- loadProject('GCAM_USA_add.dat')
# scenarios <- listScenarios(prj2)
# queries <- listQueries(prj2, 'GCAM-USA_Ref')
# 
# NEB_price <- getQuery(prj2, 'prices of all markets') %>%
#   filter(market == "globalnegative_emiss_budget")
# 
# CO2_global <- getQuery(prj2, 'CO2 emissions by region') %>%
#   group_by(scenario, year, Units) %>%
#   summarise(value = sum(value)) %>%
#   ungroup()
# 
# # NEB price zero in every time period, because FFI emissions never go net negative


# ============================================================================


# ============================================================================

# To DO List

# REVISIT CO2 emissions comparison - CO2 emissions by tech vs. emnissions (USA total, state total)

# elec prices???


# ============================================================================

logstop()
